version: '3.9'

services:
  app-dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env.dev

  app-prod:
    build:
      context: .
      target: prod
    ports:
      - '80:3000'
    env_file:
      - .env
